export let cards = [
  {
    id: "1",
    img: "/assets/laptop.png",
    off: "20% off",
    time: "Limited time",
    title: "Webbuilder 1",
    description: "Computer Modern classic with wix support",
    Price: "$49.96",
    discountPrice: "$39.96",
    discountpercentage: "20%",
    btn: "View Deal",
  },
  {
    id: "2",
    img: "/assets/laptop.png",
    off: "20% off",
    time: "Limited time",
    title: "Webbuilder 1",
    description: "Computer Modern classic with wix support",
    Price: "$49.96",
    discountPrice: "$39.96",
    discountpercentage: "20%",
    btn: "View Deal",
  },
  {
    id: "3",
    img: "/assets/laptop.png",
    off: "20% off",
    time: "Limited time",
    title: "Webbuilder 1",
    description: "Computer Modern classic with wix support",
    Price: "$49.96",
    discountPrice: "$39.96",
    discountpercentage: "20%",
    btn: "View Deal",
  },
];
